@contactId = replace_me

### Get all contacts
GET http://localhost:3000/contacts

### Get a contact by ID
GET http://localhost:3000/contacts/{{contactId}}

### Create a new contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "Rafael",
  "lastName": "Di Zeo",
  "email": "rafino@onlycats.com",
  "favoriteColor": "Orange",
  "birthday": "2024-11-15"
}

### Update a contact:
PUT http://localhost:3000/contacts/{{contactId}}
Content-Type: application/json

{
  "firstName": "Fino",
  "lastName": "Di Zeo",
  "email": "eltrapodedicarlo@la12.com",
  "favoriteColor": "Gold",
  "birthday": "2024-10-23"
}

### Delete a contact:
DELETE http://localhost:3000/contacts/{{contactId}}